"""init

Revision ID: 6b595c7689ad
Revises: 
Create Date: 2022-11-05 09:16:27.850505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b595c7689ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotel_room',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('image_url', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number', name='uix_hotel_room_number')
    )
    op.create_table('room_reservation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('date_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('guest_mobile', sa.String(length=20), nullable=False),
    sa.Column('guest_name', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['hotel_room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_reservation')
    op.drop_table('hotel_room')
    # ### end Alembic commands ###
